version: '3.8'

services:
  # Express
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_PORT: 3306
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: password
  #     MYSQL_DATABASE: mysql
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     REDIS_USER: default
  #     REDIS_PASSWORD: password
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql
  #     - redis
  #     - postgres

  # MySQL
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
    volumes:
      - mysql_data:/var/lib/mysql

  # Postgres
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: password
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  postgres_data:
